# This is a basic workflow to help you get started with Actions

name: CI - pytest

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: print github action context
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/xiaopeng163/github-actions-python.git
          cd github-actions-python
      - name: install pytest
        run: pip install pytest
      - name: pytest
        run: pytest
  
