# This is a basic workflow to help you get started with Actions

name: CI - pytest

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/xiaopeng163/github-actions-python.git
          cd github-actions-python
      - name: install pytest
        run: pip install pytest
      - name: pytest
        run: pytest
  # # This workflow contains a single job called "build"
  # build_on_ubuntu:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
  
  # build_on_windows:
  #   runs-on: windows-latest
  #   if: ${{ success() }}
  #   needs: [build_on_ubuntu]
  #   steps: 
  #     - name: run multi-line script
        # run: |
        #   echo "hello github actions"
        #   Get-Date
  
